# Generated by Django 4.2.1 on 2023-05-20 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='classID',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='enrolTime',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='gradeTime',
        ),
        migrations.AddField(
            model_name='course',
            name='courseID',
            field=models.CharField(default=1, max_length=6),
        ),
        migrations.AddField(
            model_name='semester',
            name='semesterID',
            field=models.CharField(default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='enrolled_class',
            field=models.ForeignKey(db_column='classID', default=1, on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.class'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='grade_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
